{{- if .Values.keyManager.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "orchestrate.keyManager.fullname" . }}-envmap
  labels:
    {{- include "orchestrate.keyManager.labels" . | nindent 4 }}
  annotations:
    {{- include "orchestrate.annotations" . | nindent 4 }}
data:
{{- range $key,$value := .Values.global.environment }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- range $key,$value := .Values.keyManager.environment }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}