{{- if and .Values.keyManager.enabled .Values.keyManager.vaultAgent.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "orchestrate.keyManager.fullname" . }}-vault-agent
  labels:
    {{- include "orchestrate.keyManager.labels" . | nindent 4 }}
  annotations:
    {{- include "orchestrate.annotations" . | nindent 4 }}
data:
  agent-config.hcl: |
    exit_after_auth = true
    auto_auth {
      method "kubernetes" {
       mount_path = "auth/kubernetes"
       config = {
        role = "{{ .Values.keyManager.vaultAgent.role }}"
       }
      }
      sink "file" {
        config = {
          path = "/vault/token/.vault-token"
        }
      }
    }
{{- end }}