{{- if and .Values.keyManager.enabled .Values.keyManager.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "orchestrate.keyManager.serviceAccountName" . }}
  labels:
    {{- include "orchestrate.keyManager.labels" . | nindent 4 }}
  {{- with .Values.keyManager.serviceAccount.annotations }}
  annotations:
    {{- include "orchestrate.annotations" . | nindent 4 }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}