{{- if .Values.keyManager.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "orchestrate.keyManager.fullname" . }}
  labels:
    {{- include "orchestrate.keyManager.labels" . | nindent 4 }}
  annotations:
    {{- include "orchestrate.annotations" . | nindent 4 }}
spec:
  type: {{ .Values.keyManager.service.type }}
  ports:
    - port: {{ .Values.keyManager.service.http.port }}
      targetPort: http-svc
      protocol: TCP
      name: http-svc
    - port: {{ .Values.keyManager.service.metrics.port }}
      targetPort: http-metrics
      protocol: TCP
      name: http-metrics
  selector:
    {{- include "orchestrate.keyManager.selectorLabels" . | nindent 4 }}
{{- end }}