{{- if .Values.global.imageCredentials.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "orchestrate.imagePullSecretName" . }}
  annotations:
    {{- include "orchestrate.annotations" . | nindent 4 }}
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "5"
  labels:
    {{- include "orchestrate.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "orchestrate.imagePullSecret" . }}
{{- end }}
