{{- if and (.Values.txSender.enabled) (or .Values.txSender.environmentSecrets .Values.global.environmentSecrets) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "orchestrate.txSender.fullname" . }}-secretmap
  labels:
    {{- include "orchestrate.txSender.labels" . | nindent 4 }}
  annotations:
    {{- include "orchestrate.annotations" . | nindent 4 }}
type: Opaque
data:
{{- range $key,$value := .Values.global.environmentSecrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
{{- range $key,$value := .Values.txSender.environmentSecrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
{{- end }}
