{{- if and .Values.txSender.enabled .Values.txSender.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "orchestrate.txSender.serviceAccountName" . }}
  labels:
    {{- include "orchestrate.txSender.labels" . | nindent 4 }}
  {{- with .Values.txSender.serviceAccount.annotations }}
  annotations:
    {{- include "orchestrate.annotations" . | nindent 4 }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
