{{- if .Values.api.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "orchestrate.api.fullname" . }}-hook-envmap
  labels:
    {{- include "orchestrate.api.labels" . | nindent 4 }}
  annotations:
    {{- include "orchestrate.annotations" . | nindent 4 }}
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded
data:
{{- range $key,$value := .Values.global.environment }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- range $key,$value := .Values.api.environment }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
