{{- if .Values.api.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "orchestrate.api.fullname" . }}-envmap
  labels:
    {{- include "orchestrate.api.labels" . | nindent 4 }}
  annotations:
    {{- include "orchestrate.annotations" . | nindent 4 }}
data:
{{- range $key,$value := .Values.global.environment }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- range $key,$value := .Values.api.environment }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
{{- end }}
