{{- if and (.Values.api.enabled) (or .Values.api.environmentSecrets .Values.global.environmentSecrets) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "orchestrate.api.fullname" . }}-hook-secretmap
  labels:
    {{- include "orchestrate.api.labels" . | nindent 4 }}
  annotations:
    {{- include "orchestrate.annotations" . | nindent 4 }}
type: Opaque
data:
{{- range $key,$value := .Values.global.environmentSecrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
{{- range $key,$value := .Values.api.environmentSecrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
{{- end }}

