---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "orchestrate.api.fullname" . }}-account-import
  labels:
    {{- include "orchestrate.api.labels" . | nindent 4 }}
  annotations:
    {{- include "orchestrate.annotations" . | nindent 4 }}
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  backoffLimit: {{ .Values.api.backoffLimit }}
  template:
    metadata:
      name: account-import
      labels:
        {{- include "orchestrate.api.labels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      {{- if .Values.global.imageCredentials }}
      imagePullSecrets:
        - name: {{ include "orchestrate.imagePullSecretName" . }}
      {{- end }}
      containers:
        - name: {{ template "orchestrate.api.fullname" . }}-account-import
          image: "{{ .Values.global.image.repository }}:{{ .Values.global.image.tag }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          command:
            - /go/bin/main
          args:
            - api
            - account
            - import
          envFrom:
            - configMapRef:
                name: {{ include "orchestrate.api.fullname" . }}-envmap
            {{- if .Values.api.environmentSecrets }}
            - secretRef:
                name: {{ include "orchestrate.api.fullname" . }}-secretmap
                optional: true
            {{- end }}
            {{- if .Values.api.existingSecret }}
            - secretRef:
                name: {{ .Values.api.existingSecret }}
                optional: true
            {{- end }}

