{{- if and .Values.api.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "orchestrate.api.fullname" . }}-hook-envmap
  annotations:
    {{- include "orchestrate.annotations" . | nindent 4 }}
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
  labels:
    {{- include "orchestrate.api.labels" . | nindent 4 }}
data:
{{- range $key,$value := .Values.api.environment }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- if and .Values.api.enabled .Values.api.environmentSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "orchestrate.api.fullname" . }}-hook-secretmap
  annotations:
    {{- include "orchestrate.annotations" . | nindent 4 }}
    "helm.sh/hook": pre-install, pre_update
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
  labels:
    {{- include "orchestrate.api.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key,$value := .Values.api.environmentSecrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
{{- end }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "orchestrate.api.fullname" . }}-migrate-init-job
  labels:
    {{- include "orchestrate.api.labels" . | nindent 4 }}
  annotations:
    {{- include "orchestrate.annotations" . | nindent 4 }}
    "helm.sh/hook": pre-install, pre_update
    "helm.sh/hook-weight": "10"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  backoffLimit: {{ .Values.migrate.backoffLimit }}
  template:
    metadata:
      name: migrate-init
      labels:
        {{- include "orchestrate.api.labels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      {{- if .Values.global.imageCredentials }}
      imagePullSecrets:
        - name: {{ include "orchestrate.imagePullSecretName" . }}
      {{- end }}
      containers:
        - name: {{ template "orchestrate.api.fullname" . }}-init-up-db
          image: "{{ .Values.global.image.repository }}:{{ .Values.global.image.tag }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          command:
            - /go/bin/main
          args:
            - api
            - migrate
            - up
          envFrom:
            - configMapRef:
                name: {{ include "orchestrate.api.fullname" . }}-hook-envmap
            {{- if .Values.migrate.environmentSecrets }}
            - secretRef:
                name: {{ include "orchestrate.api.fullname" . }}-hook-secretmap
                optional: true
            {{- end }}
            {{- if .Values.api.existingSecret }}
            - secretRef:
                name: {{ .Values.migrate.existingSecret }}
                optional: true
            {{- end }}
{{- end }}
