{{- if and .Values.api.enabled .Values.api.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "orchestrate.api.serviceAccountName" . }}
  labels:
    {{- include "orchestrate.api.labels" . | nindent 4 }}
  {{- with .Values.api.serviceAccount.annotations }}
  annotations:
    {{- include "orchestrate.annotations" . | nindent 4 }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}